///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContentInRing
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear4' at 11;11.", repo.ShowsWWE.DropMeWhereIShouldAppear4Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW7' at 11;11.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW7Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW7.MoveTo("11;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_AJLeeNID26179099SuperstarsDiva()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SomeTableTag.AJLeeNID26179099SuperstarsDiva' at 30;5.", repo.ShowsWWE.SomeTableTag.AJLeeNID26179099SuperstarsDivaInfo);
            repo.ShowsWWE.SomeTableTag.AJLeeNID26179099SuperstarsDiva.Click("30;5");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW1' at 8;11.", repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW1.Click("8;11");
        }

        public void Mouse_Click_AidenEnglishNID26179098Supersta()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SomeTableTag.AidenEnglishNID26179098Supersta' at 41;9.", repo.ShowsWWE.SomeTableTag.AidenEnglishNID26179098SuperstaInfo);
            repo.ShowsWWE.SomeTableTag.AidenEnglishNID26179098Supersta.Click("41;9");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW' at 13;11.", repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsWInfo);
            repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW.Click("13;11");
        }

        public void Mouse_Click_AdrianNevilleNID26179097Superst()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SomeTableTag.AdrianNevilleNID26179097Superst' at 13;4.", repo.ShowsWWE.SomeTableTag.AdrianNevilleNID26179097SuperstInfo);
            repo.ShowsWWE.SomeTableTag.AdrianNevilleNID26179097Superst.Click("13;4");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW8()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW8' at 8;8.", repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW8Info);
            repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW8.Click("8;8");
        }

        public void Mouse_Click_TdTagStoneColdSteveAustin()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweBrowserNoderefTable1.TdTagStoneColdSteveAustin' at 90;14.", repo.ShowsWWE.WweBrowserNoderefTable1.TdTagStoneColdSteveAustinInfo);
            repo.ShowsWWE.WweBrowserNoderefTable1.TdTagStoneColdSteveAustin.Click("90;14");
        }

        public void Mouse_Click_ATagStoneColdSteveAustinNID261790()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SomeTableTag.ATagStoneColdSteveAustinNID261790' at 37;3.", repo.ShowsWWE.SomeTableTag.ATagStoneColdSteveAustinNID261790Info);
            repo.ShowsWWE.SomeTableTag.ATagStoneColdSteveAustinNID261790.Click("37;3");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW7()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW7' at 8;10.", repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW7Info);
            repo.ShowsWWE.WweBrowserNoderefTable1.HttpQaWweAppCloud6WweComFeedsW7.Click("8;10");
        }

        public void Mouse_Click_InTheRing()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.InTheRing' at 76;14.", repo.ShowsWWE.InTheRingInfo);
           // repo.ShowsWWE.InTheRing.Click("76;14");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-1']/a[@innertext='In The Ring']");
        }
	   public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        public void Key_Sequence_EditIntheringValues3Nid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varInRing4 with focus on 'ShowsWWE.EditIntheringValues3Nid'.", repo.ShowsWWE.EditIntheringValues3NidInfo);
             repo.ShowsWWE.EditIntheringValues3Nid.PressKeys("{Back}");
            repo.ShowsWWE.EditIntheringValues3Nid.PressKeys(varInRing4);
        }

        public void Key_Sequence_EditIntheringValues2Nid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varInRing3 with focus on 'ShowsWWE.EditIntheringValues2Nid'.", repo.ShowsWWE.EditIntheringValues2NidInfo);
             repo.ShowsWWE.EditIntheringValues2Nid.PressKeys("{Back}");
            repo.ShowsWWE.EditIntheringValues2Nid.PressKeys(varInRing3);
        }

        public void Key_Sequence_EditIntheringValues1Nid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varInRing2 with focus on 'ShowsWWE.EditIntheringValues1Nid'.", repo.ShowsWWE.EditIntheringValues1NidInfo);
             repo.ShowsWWE.EditIntheringValues1Nid.PressKeys("{Back}");
            repo.ShowsWWE.EditIntheringValues1Nid.PressKeys(varInRing2);
        }

        public void Key_Sequence_EditIntheringValues0Nid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varInRing1 with focus on 'ShowsWWE.EditIntheringValues0Nid'.", repo.ShowsWWE.EditIntheringValues0NidInfo);
            repo.ShowsWWE.EditIntheringValues0Nid.PressKeys("{Delete}");
            repo.ShowsWWE.EditIntheringValues0Nid.PressKeys(varInRing1);
        }
        public void pressTab()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.");
            Keyboard.Press("{Tab 3}");
        }
             
    }
}