///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContentPhotoGroup
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

       

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear3' at 7;13.", repo.ShowsWWE.DropMeWhereIShouldAppear3Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Ranorex.Delay.Seconds(1);
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW6' at 7;13.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW6Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW6.MoveTo("7;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
             Ranorex.Delay.Seconds(1);
        }

        public void Mouse_Click_ATag20150105Raw16ComingsoonJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20150105Raw16ComingsoonJpg' at 88;4.", repo.ShowsWWE.Results.ATag20150105Raw16ComingsoonJpgInfo);
            repo.ShowsWWE.Results.ATag20150105Raw16ComingsoonJpg.Click("88;4");
        }

        public void Mouse_Click_ATag172()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 9;8.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.Click("9;8");
        }

        public void Mouse_Click_ATag012()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 10;7.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.Click("10;7");
        }

        public void Mouse_Click_ATag201512()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20151' at 19;7.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.Click("19;7");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW' at 6;8.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsWInfo);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW.Click("6;8");
        }

        public void Mouse_Up_WweFeedWweactiveFormStillgroup()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup' at 277;273.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroupInfo);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup.MoveTo("277;273");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormStillgroup()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup' at 277;181.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroupInfo);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup.MoveTo("277;181");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_ATag20150105RawThennowJpg1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20150105RawThennowJpg' at 67;7.", repo.ShowsWWE.Results.ATag20150105RawThennowJpgInfo);
            repo.ShowsWWE.Results.ATag20150105RawThennowJpg.Click("67;7");
        }

        public void Mouse_Click_ATag171()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 1;8.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.Click("1;8");
        }

        public void Mouse_Click_ATag011()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 9;4.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.Click("9;4");
        }

        public void Mouse_Click_ATag201511()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20151' at 15;6.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.Click("15;6");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW7()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW7' at 8;6.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW7Info);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW7.Click("8;6");
        }

        public void Mouse_Click_ATag20150105RawThennowJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20150105RawThennowJpg' at 67;8.", repo.ShowsWWE.Results.ATag20150105RawThennowJpgInfo);
            repo.ShowsWWE.Results.ATag20150105RawThennowJpg.Click("67;8");
        }

        public void Mouse_Click_ATag17()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 6;9.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.Click("6;9");
        }

        public void Mouse_Click_ATag01()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 6;6.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.Click("6;6");
        }

        public void Mouse_Click_ATag20151()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20151' at 11;9.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.Click("11;9");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW6()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW6' at 6;9.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW6Info);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.HttpQaWweAppCloud6WweComFeedsW6.Click("6;9");
        }

        public void Key_Sequence_EditStillgroupTitle()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}D{LShiftKey up}emo{LShiftKey down}T{LShiftKey up}est' with focus on 'ShowsWWE.EditStillgroupTitle'.", repo.ShowsWWE.EditStillgroupTitleInfo);
            repo.ShowsWWE.EditStillgroupTitle.PressKeys("{LShiftKey down}D{LShiftKey up}emo{LShiftKey down}T{LShiftKey up}est");
        }

        public void Mouse_Click_EditStillgroupTitle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditStillgroupTitle' at 65;11.", repo.ShowsWWE.EditStillgroupTitleInfo);
            repo.ShowsWWE.EditStillgroupTitle.Click("65;11");
        }

        public void Mouse_Click_PhotoGroup()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.PhotoGroup' at 80;12.", repo.ShowsWWE.PhotoGroupInfo);
           // repo.ShowsWWE.PhotoGroup.Click("80;12");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-5']/a[@innertext='Photo Group']");
             
        }
        public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        public void Key_Sequence_EditStillgroupPhoto3Fid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varImg3NID with focus on 'ShowsWWE.EditStillgroupPhoto3Fid'.", repo.ShowsWWE.EditStillgroupPhoto3FidInfo);
             repo.ShowsWWE.EditStillgroupPhoto3Fid.PressKeys("{Back}");
            repo.ShowsWWE.EditStillgroupPhoto3Fid.PressKeys(varImg3NID);
        }

        public void Mouse_Up_WweFeedWweactiveFormStillgroup1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup' at 276;257.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroupInfo);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup.MoveTo("276;257");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormStillgroup1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup' at 272;176.", repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroupInfo);
            repo.ShowsWWE.WweFeedWweactiveFormStillgroup1.WweFeedWweactiveFormStillgroup.MoveTo("272;176");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditStillgroupPhoto2Fid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varImg2NID with focus on 'ShowsWWE.EditStillgroupPhoto2Fid'.", repo.ShowsWWE.EditStillgroupPhoto2FidInfo);
            repo.ShowsWWE.EditStillgroupPhoto2Fid.PressKeys("{Back}");
            repo.ShowsWWE.EditStillgroupPhoto2Fid.PressKeys(varImg2NID);
        }

        public void Key_Sequence_EditStillgroupPhoto1Fid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varImg1NID with focus on 'ShowsWWE.EditStillgroupPhoto1Fid'.", repo.ShowsWWE.EditStillgroupPhoto1FidInfo);
            repo.ShowsWWE.EditStillgroupPhoto1Fid.PressKeys("{Back}");
            repo.ShowsWWE.EditStillgroupPhoto1Fid.PressKeys(varImg1NID);
        }

        public void Mouse_Click_EditStillgroupPhoto1Fid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditStillgroupPhoto1Fid' at 49;7.", repo.ShowsWWE.EditStillgroupPhoto1FidInfo);
            repo.ShowsWWE.EditStillgroupPhoto1Fid.Click("49;7");
        }
         public void pressTab()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.");
            Keyboard.Press("{Tab 3}");
        }
    }
}