///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContentTrivia
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear7' at 5;16.", repo.ShowsWWE.DropMeWhereIShouldAppear7Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Down item 'ShowsWWE.HttpWweDevWweAppCloud14WweComF3' at 5;16.", repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF3Info);
            repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF3.MoveTo("5;16");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_Content()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Up item 'ShowsWWE.Content' at 301;561.", repo.ShowsWWE.ContentInfo);
            repo.ShowsWWE.Content.MoveTo("301;561");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormTrivia3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Down item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 279;139.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
            repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("279;139");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditTriviaQ1A4()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varAnswer4 with focus on 'ShowsWWE.EditTriviaQ1A4'.", repo.ShowsWWE.EditTriviaQ1A4Info);
            repo.ShowsWWE.EditTriviaQ1A4.PressKeys(varAnswer4);
        }

        public void Mouse_Click_EditTriviaQ1A4()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaQ1A4' at 127;5.", repo.ShowsWWE.EditTriviaQ1A4Info);
            repo.ShowsWWE.EditTriviaQ1A4.Click("127;5");
        }

        public void Key_Sequence_EditTriviaQ1A3()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varAnswer3 with focus on 'ShowsWWE.EditTriviaQ1A3'.", repo.ShowsWWE.EditTriviaQ1A3Info);
            repo.ShowsWWE.EditTriviaQ1A3.PressKeys(varAnswer3);
        }

        public void Mouse_Click_EditTriviaQ1A3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaQ1A3' at 135;16.", repo.ShowsWWE.EditTriviaQ1A3Info);
            repo.ShowsWWE.EditTriviaQ1A3.Click("135;16");
        }

        public void Mouse_Up_WweFeedWweactiveFormTrivia2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Up item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 279;138.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
            repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("279;138");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormTrivia2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Down item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 277;97.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
            repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("277;97");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditTriviaQ1A2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varAnswer2 with focus on 'ShowsWWE.EditTriviaQ1A2'.", repo.ShowsWWE.EditTriviaQ1A2Info);
            repo.ShowsWWE.EditTriviaQ1A2.PressKeys(varAnswer2);
        }

        public void Mouse_Click_EditTriviaQ1A2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaQ1A2' at 65;3.", repo.ShowsWWE.EditTriviaQ1A2Info);
            repo.ShowsWWE.EditTriviaQ1A2.Click("65;3");
        }

        public void Key_Sequence_EditTriviaQ1A1()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varAnswer1 with focus on 'ShowsWWE.EditTriviaQ1A1'.", repo.ShowsWWE.EditTriviaQ1A1Info);
            repo.ShowsWWE.EditTriviaQ1A1.PressKeys(varAnswer1);
        }

        public void Mouse_DoubleClick_EditTriviaQ1A1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left DoubleClick item 'ShowsWWE.EditTriviaQ1A1' at 71;9.", repo.ShowsWWE.EditTriviaQ1A1Info);
            repo.ShowsWWE.EditTriviaQ1A1.DoubleClick("71;9");
        }

        public void Set_Value_EditTriviaQ1Correct()
        {
            Report.Log(ReportLevel.Info, "Set Value", "(Optional Action)\r\nSetting attribute TagValue to '$varCorrectAns' on item 'ShowsWWE.EditTriviaQ1Correct'.", repo.ShowsWWE.EditTriviaQ1CorrectInfo);
            repo.ShowsWWE.EditTriviaQ1Correct.Element.SetAttributeValue("TagValue", varCorrectAns);
        }

        public void Key_Sequence_EditTriviaQ1()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varQuestion1 with focus on 'ShowsWWE.EditTriviaQ1'.", repo.ShowsWWE.EditTriviaQ1Info);
            repo.ShowsWWE.EditTriviaQ1.PressKeys(varQuestion1);
        }

        public void Mouse_Click_EditTriviaQ1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaQ1' at 118;9.", repo.ShowsWWE.EditTriviaQ1Info);
            repo.ShowsWWE.EditTriviaQ1.Click("118;9");
        }

        public void Key_Sequence_EditTriviaCloserLoseText()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varIncorrectText with focus on 'ShowsWWE.EditTriviaCloserLoseText'.", repo.ShowsWWE.EditTriviaCloserLoseTextInfo);
            repo.ShowsWWE.EditTriviaCloserLoseText.PressKeys(varIncorrectText);
        }

        public void Mouse_Click_EditTriviaCloserLoseText()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaCloserLoseText' at 100;16.", repo.ShowsWWE.EditTriviaCloserLoseTextInfo);
            repo.ShowsWWE.EditTriviaCloserLoseText.Click("100;16");
        }

        public void Mouse_Up_WweFeedWweactiveFormTrivia1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Up item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 280;107.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
            repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("280;107");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormTrivia1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Down item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 273;70.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
            repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("273;70");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditTriviaCloserWinText()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varCorrectText with focus on 'ShowsWWE.EditTriviaCloserWinText'.", repo.ShowsWWE.EditTriviaCloserWinTextInfo);
            repo.ShowsWWE.EditTriviaCloserWinText.PressKeys(varCorrectText);
        }

        public void Mouse_Click_EditTriviaCloserWinText()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaCloserWinText' at 201;4.", repo.ShowsWWE.EditTriviaCloserWinTextInfo);
            repo.ShowsWWE.EditTriviaCloserWinText.Click("201;4");
        }

        public void Key_Sequence_EditTriviaCloserLoseFid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varCloserLose with focus on 'ShowsWWE.EditTriviaCloserLoseFid'.", repo.ShowsWWE.EditTriviaCloserLoseFidInfo);
            repo.ShowsWWE.EditTriviaCloserLoseFid.PressKeys(varCloserLose);
        }

        public void Mouse_Click_EditTriviaCloserLoseFid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaCloserLoseFid' at 62;-1.", repo.ShowsWWE.EditTriviaCloserLoseFidInfo);
           // repo.ShowsWWE.EditTriviaCloserLoseFid.Click("62;-1");
           clickOnObject("/dom[@caption='WWE']//input[#'edit-trivia-closer-lose-fid']");
           repo.ShowsWWE.EditTriviaCloserLoseFid.PressKeys("{Back}");
        }

        public void Key_Sequence_EditTriviaCloserWinFid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varCloserWin with focus on 'ShowsWWE.EditTriviaCloserWinFid'.", repo.ShowsWWE.EditTriviaCloserWinFidInfo);
            repo.ShowsWWE.EditTriviaCloserWinFid.PressKeys(varCloserWin);
        }

        public void Mouse_Click_EditTriviaCloserWinFid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaCloserWinFid' at 44;15.", repo.ShowsWWE.EditTriviaCloserWinFidInfo);
            //repo.ShowsWWE.EditTriviaCloserWinFid.Click("44;15");
            clickOnObject("/dom[@caption='WWE']//input[#'edit-trivia-closer-win-fid']");
            repo.ShowsWWE.EditTriviaCloserWinFid.PressKeys("{Back}");
        }

        public void Mouse_Up_WweFeedWweactiveFormTrivia()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Up item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 281;93.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
           // repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("281;93");
           // Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_WweFeedWweactiveFormTrivia()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Down item 'ShowsWWE.WweFeedWweactiveFormTrivia' at 275;66.", repo.ShowsWWE.WweFeedWweactiveFormTriviaInfo);
           // repo.ShowsWWE.WweFeedWweactiveFormTrivia.MoveTo("275;66");
           // Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditTriviaOpenerFid1()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varOpenerGraphic with focus on 'ShowsWWE.EditTriviaOpenerFid'.", repo.ShowsWWE.EditTriviaOpenerFidInfo);
            repo.ShowsWWE.EditTriviaOpenerFid.PressKeys(varOpenerGraphic);
        }

        public void Key_Sequence_EditTriviaOpenerFid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence '{Back}' with focus on 'ShowsWWE.EditTriviaOpenerFid'.", repo.ShowsWWE.EditTriviaOpenerFidInfo);
            repo.ShowsWWE.EditTriviaOpenerFid.PressKeys("{Back}");
        }

        public void Mouse_Click_EditTriviaOpenerFid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaOpenerFid' at 105;7.", repo.ShowsWWE.EditTriviaOpenerFidInfo);
            //repo.ShowsWWE.EditTriviaOpenerFid.Click("105;7");
            clickOnObject("/dom[@caption='WWE']//input[#'edit-trivia-opener-fid']");
            Ranorex.Delay.Seconds(1);
            //repo.ShowsWWE.EditTriviaOpenerFid.PressKeys("{Back}");
        }

        public void Key_Sequence_EditTriviaTitle()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)\r\nKey sequence from variable $varTitle with focus on 'ShowsWWE.EditTriviaTitle'.", repo.ShowsWWE.EditTriviaTitleInfo);
            repo.ShowsWWE.EditTriviaTitle.PressKeys(varTitle);
        }

        public void Mouse_Click_EditTriviaTitle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.EditTriviaTitle' at 142;8.", repo.ShowsWWE.EditTriviaTitleInfo);
            //repo.ShowsWWE.EditTriviaTitle.Click("142;8");
        }

        public void Mouse_Click_Trivia()
        {
            Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ShowsWWE.Trivia' at 56;7.", repo.ShowsWWE.TriviaInfo);
            //repo.ShowsWWE.Trivia.Click("56;7");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-9']/a[@innertext='Trivia']");
        }

       

   		  public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

      
    }
}