///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContent_YouTube
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Key_Sequence_EditYtid(String yTubeId)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345' with focus on 'ShowsWWE.EditYtid'.", repo.ShowsWWE.EditYtidInfo);
            repo.ShowsWWE.EditYtid.PressKeys(yTubeId);
        }

        public void Mouse_Click_EditYtid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditYtid' at 82;15.", repo.ShowsWWE.EditYtidInfo);
           // repo.ShowsWWE.EditYtid.Click("82;15");
           clickOnObject("/dom[@caption='WWE']//input[#'edit-ytid']");
        }

        public void Mouse_ClickOnYouTube()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.UiAccordionAccordionHeader7' at 121;9.", repo.ShowsWWE.UiAccordionAccordionHeader7Info);
            //repo.ShowsWWE.UiAccordionAccordionHeader7.Click("121;9");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-7']/a[@innertext='YouTube']");
            
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear5' at 14;5.", repo.ShowsWWE.DropMeWhereIShouldAppear5Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpWweDevWweAppCloud14WweComF1' at 14;5.", repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF1Info);
            repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF1.MoveTo("14;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }
        public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        public void Mouse_Down_HttpWweDevWweAppCloud14WweComF1()
        {
        }
    }
}