///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addContentInRing recording.
    /// </summary>
    [TestModule("31c7471a-4117-420b-a841-8221b3302451", ModuleType.Recording, 1)]
    public partial class AddContentInRing : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentInRing instance = new AddContentInRing();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentInRing()
        {
            varInRing1 = "43563453";
            varInRing2 = "090800";
            varInRing3 = "89789877";
            varInRing4 = "098000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentInRing Instance
        {
            get { return instance; }
        }

#region Variables

        string _varInRing1;

        /// <summary>
        /// Gets or sets the value of variable varInRing1.
        /// </summary>
        [TestVariable("d57c27ba-dabe-444f-9231-666723476862")]
        public string varInRing1
        {
            get { return _varInRing1; }
            set { _varInRing1 = value; }
        }

        string _varInRing2;

        /// <summary>
        /// Gets or sets the value of variable varInRing2.
        /// </summary>
        [TestVariable("2d8fcc0a-b566-4b48-bf54-379620aa44e1")]
        public string varInRing2
        {
            get { return _varInRing2; }
            set { _varInRing2 = value; }
        }

        string _varInRing3;

        /// <summary>
        /// Gets or sets the value of variable varInRing3.
        /// </summary>
        [TestVariable("f74e95c4-1ada-47ad-a312-a6f9a8e3dab7")]
        public string varInRing3
        {
            get { return _varInRing3; }
            set { _varInRing3 = value; }
        }

        string _varInRing4;

        /// <summary>
        /// Gets or sets the value of variable varInRing4.
        /// </summary>
        [TestVariable("a6819c6e-b493-4292-b8c4-724286d7a8c8")]
        public string varInRing4
        {
            get { return _varInRing4; }
            set { _varInRing4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_InTheRing();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditIntheringValues0Nid();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditIntheringValues1Nid();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditIntheringValues2Nid();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditIntheringValues3Nid();
            Delay.Milliseconds(0);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
