///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContentVideo
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear2' at 11;15.", repo.ShowsWWE.DropMeWhereIShouldAppear2Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW5' at 11;15.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW5Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW5.MoveTo("11;15");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_DanielBryanVsTheBigShowContinues()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.DanielBryanVsTheBigShowContinues' at 60;8.", repo.ShowsWWE.DanielBryanVsTheBigShowContinuesInfo);
            repo.ShowsWWE.DanielBryanVsTheBigShowContinues.Click("60;8");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW4()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW4' at 10;12.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW4Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW4.Click("10;12");
        }

        public void Mouse_Click_VideoVOD()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.VideoVOD' at 63;13.", repo.ShowsWWE.VideoVODInfo);
            //repo.ShowsWWE.VideoVOD.Click("63;13");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-2']/a[@innertext='Video VOD']");
        }
		 public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        public void Mouse_Up_DropMeWhereIShouldAppear2()
        {
        }

        public void Key_Sequence_EditVideoNid(String videoNID)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1234566' with focus on 'ShowsWWE.EditVideoNid'.", repo.ShowsWWE.EditVideoNidInfo);
            repo.ShowsWWE.EditVideoNid.PressKeys(videoNID);
        }
    }
}