///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addContentVideo recording.
    /// </summary>
    [TestModule("1194bd2c-4de9-4f2d-96d2-57e7730a3d48", ModuleType.Recording, 1)]
    public partial class AddContentVideo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentVideo instance = new AddContentVideo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentVideo()
        {
            varVideoNID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentVideo Instance
        {
            get { return instance; }
        }

#region Variables

        string _varVideoNID;

        /// <summary>
        /// Gets or sets the value of variable varVideoNID.
        /// </summary>
        [TestVariable("60d0704a-9820-4585-8c88-46c7bc909115")]
        public string varVideoNID
        {
            get { return _varVideoNID; }
            set { _varVideoNID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1000ms.", new RecordItemIndex(0));
            Delay.Duration(1000, false);
            
            Mouse_Click_VideoVOD();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditVideoNid(varVideoNID);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1000ms.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
