///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddContentTrivia recording.
    /// </summary>
    [TestModule("1e89e17a-0fcf-407f-bb42-eac7337c3f5f", ModuleType.Recording, 1)]
    public partial class AddContentTrivia : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentTrivia instance = new AddContentTrivia();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentTrivia()
        {
            varTitle = "title";
            varOpenerGraphic = "1233";
            varCloserWin = "{Back}456";
            varCloserLose = "{Back}890";
            varCorrectText = "correctText";
            varIncorrectText = "abc";
            varQuestion1 = "question1";
            varCorrectAns = "2";
            varAnswer1 = "123";
            varAnswer2 = "456";
            varAnswer3 = "987";
            varAnswer4 = "76767";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentTrivia Instance
        {
            get { return instance; }
        }

#region Variables

        string _varTitle;

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("8dedfab8-5991-4046-8698-451d83d6bc9b")]
        public string varTitle
        {
            get { return _varTitle; }
            set { _varTitle = value; }
        }

        string _varOpenerGraphic;

        /// <summary>
        /// Gets or sets the value of variable varOpenerGraphic.
        /// </summary>
        [TestVariable("2d8bf076-e565-4c12-bba5-839ed7fc6d6f")]
        public string varOpenerGraphic
        {
            get { return _varOpenerGraphic; }
            set { _varOpenerGraphic = value; }
        }

        string _varCloserWin;

        /// <summary>
        /// Gets or sets the value of variable varCloserWin.
        /// </summary>
        [TestVariable("2c3d7635-92cd-4d23-b985-66ac9510c1e8")]
        public string varCloserWin
        {
            get { return _varCloserWin; }
            set { _varCloserWin = value; }
        }

        string _varCloserLose;

        /// <summary>
        /// Gets or sets the value of variable varCloserLose.
        /// </summary>
        [TestVariable("4a701a4a-8243-4481-9962-ddd45ab2afca")]
        public string varCloserLose
        {
            get { return _varCloserLose; }
            set { _varCloserLose = value; }
        }

        string _varCorrectText;

        /// <summary>
        /// Gets or sets the value of variable varCorrectText.
        /// </summary>
        [TestVariable("e976f383-021c-4eca-a357-e11602d992e8")]
        public string varCorrectText
        {
            get { return _varCorrectText; }
            set { _varCorrectText = value; }
        }

        string _varIncorrectText;

        /// <summary>
        /// Gets or sets the value of variable varIncorrectText.
        /// </summary>
        [TestVariable("fd0aed64-269d-4ad6-ae7a-b8831f7bb7c8")]
        public string varIncorrectText
        {
            get { return _varIncorrectText; }
            set { _varIncorrectText = value; }
        }

        string _varQuestion1;

        /// <summary>
        /// Gets or sets the value of variable varQuestion1.
        /// </summary>
        [TestVariable("c7aa4fd7-6eba-4126-911e-769946fbe116")]
        public string varQuestion1
        {
            get { return _varQuestion1; }
            set { _varQuestion1 = value; }
        }

        string _varCorrectAns;

        /// <summary>
        /// Gets or sets the value of variable varCorrectAns.
        /// </summary>
        [TestVariable("892fe451-0f04-48aa-9cec-17067da0f13f")]
        public string varCorrectAns
        {
            get { return _varCorrectAns; }
            set { _varCorrectAns = value; }
        }

        string _varAnswer1;

        /// <summary>
        /// Gets or sets the value of variable varAnswer1.
        /// </summary>
        [TestVariable("8f338cf2-4033-48bb-8db9-2dbfc4654a09")]
        public string varAnswer1
        {
            get { return _varAnswer1; }
            set { _varAnswer1 = value; }
        }

        string _varAnswer2;

        /// <summary>
        /// Gets or sets the value of variable varAnswer2.
        /// </summary>
        [TestVariable("262cfbe8-c597-4f98-a6d2-88a85d3dbb25")]
        public string varAnswer2
        {
            get { return _varAnswer2; }
            set { _varAnswer2 = value; }
        }

        string _varAnswer3;

        /// <summary>
        /// Gets or sets the value of variable varAnswer3.
        /// </summary>
        [TestVariable("8426691c-d95b-4999-b5d4-ebd7c7c3f25b")]
        public string varAnswer3
        {
            get { return _varAnswer3; }
            set { _varAnswer3 = value; }
        }

        string _varAnswer4;

        /// <summary>
        /// Gets or sets the value of variable varAnswer4.
        /// </summary>
        [TestVariable("22b305fd-1b11-46c8-b339-3606dfd66517")]
        public string varAnswer4
        {
            get { return _varAnswer4; }
            set { _varAnswer4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_Trivia();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Mouse_Click_EditTriviaTitle();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaTitle();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaOpenerFid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaOpenerFid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaOpenerFid1();
            Delay.Milliseconds(0);
            
            Mouse_Down_WweFeedWweactiveFormTrivia();
            Delay.Milliseconds(0);
            
            Mouse_Up_WweFeedWweactiveFormTrivia();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaCloserWinFid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaCloserWinFid();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaCloserLoseFid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaCloserLoseFid();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaCloserWinText();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaCloserWinText();
            Delay.Milliseconds(0);
            
            Mouse_Down_WweFeedWweactiveFormTrivia1();
            Delay.Milliseconds(0);
            
            Mouse_Up_WweFeedWweactiveFormTrivia1();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaCloserLoseText();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaCloserLoseText();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaQ1();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaQ1();
            Delay.Milliseconds(0);
            
            Set_Value_EditTriviaQ1Correct();
            Delay.Milliseconds(0);
            
            Mouse_DoubleClick_EditTriviaQ1A1();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaQ1A1();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaQ1A2();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaQ1A2();
            Delay.Milliseconds(0);
            
            Mouse_Down_WweFeedWweactiveFormTrivia2();
            Delay.Milliseconds(0);
            
            Mouse_Up_WweFeedWweactiveFormTrivia2();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaQ1A3();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaQ1A3();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditTriviaQ1A4();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTriviaQ1A4();
            Delay.Milliseconds(0);
            
            Mouse_Down_WweFeedWweactiveFormTrivia3();
            Delay.Milliseconds(0);
            
            Mouse_Up_Content();
            Delay.Milliseconds(0);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
