///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addContentPhoto recording.
    /// </summary>
    [TestModule("6f4ad8af-d579-46a8-9c14-49024656026a", ModuleType.Recording, 1)]
    public partial class AddContentPhoto : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentPhoto instance = new AddContentPhoto();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentPhoto()
        {
            varPhotoTitle = "";
            varPhotoNID = "123456";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentPhoto Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPhotoTitle;

        /// <summary>
        /// Gets or sets the value of variable varPhotoTitle.
        /// </summary>
        [TestVariable("144be99c-4663-4285-b489-a7b09089f0fa")]
        public string varPhotoTitle
        {
            get { return _varPhotoTitle; }
            set { _varPhotoTitle = value; }
        }

        string _varPhotoNID;

        /// <summary>
        /// Gets or sets the value of variable varPhotoNID.
        /// </summary>
        [TestVariable("210b7854-1a31-485a-aa82-5b7785d1d244")]
        public string varPhotoNID
        {
            get { return _varPhotoNID; }
            set { _varPhotoNID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            ClickOnPhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            // For Photo title
            Mouse_Down_EditPhotoTitle(varPhotoTitle);
            Delay.Milliseconds(0);
            
            Mouse_Up_EditPhotoTitle();
            Delay.Milliseconds(0);
            
            Mouse_Down_EditPhotoTitleStyle();
            Delay.Milliseconds(0);
            
            Mouse_Up_EditPhotoTitleStyle();
            Delay.Milliseconds(0);
            
            Mouse_Down_Dropdown();
            Delay.Milliseconds(0);
            
            Mouse_Up_Dropdown();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditPhotoFid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditPhotoFid3();
            Delay.Milliseconds(0);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
