///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addContentPhotoGroup recording.
    /// </summary>
    [TestModule("127cb86c-09d0-43c6-9ffa-689c7b68fa48", ModuleType.Recording, 1)]
    public partial class AddContentPhotoGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentPhotoGroup instance = new AddContentPhotoGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentPhotoGroup()
        {
            varImg1NID = "111111";
            varImg2NID = "2222222";
            varImg3NID = "33333";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentPhotoGroup Instance
        {
            get { return instance; }
        }

#region Variables

        string _varImg1NID;

        /// <summary>
        /// Gets or sets the value of variable varImg1NID.
        /// </summary>
        [TestVariable("efdb4ba4-02f4-4251-9d03-94552c41d6be")]
        public string varImg1NID
        {
            get { return _varImg1NID; }
            set { _varImg1NID = value; }
        }

        string _varImg2NID;

        /// <summary>
        /// Gets or sets the value of variable varImg2NID.
        /// </summary>
        [TestVariable("53247a59-c24e-4074-953b-6eb8ff5717af")]
        public string varImg2NID
        {
            get { return _varImg2NID; }
            set { _varImg2NID = value; }
        }

        string _varImg3NID;

        /// <summary>
        /// Gets or sets the value of variable varImg3NID.
        /// </summary>
        [TestVariable("bd470ce7-473a-4b4a-9f1c-66185e591eb5")]
        public string varImg3NID
        {
            get { return _varImg3NID; }
            set { _varImg3NID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_PhotoGroup();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditStillgroupTitle();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditStillgroupTitle();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditStillgroupPhoto1Fid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditStillgroupPhoto1Fid();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditStillgroupPhoto2Fid();
            Delay.Milliseconds(0);
            
            pressTab();
            Delay.Milliseconds(0);
            
            Mouse_Down_WweFeedWweactiveFormStillgroup1();
            Delay.Milliseconds(0);
            
            Mouse_Up_WweFeedWweactiveFormStillgroup1();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditStillgroupPhoto3Fid();
            Delay.Milliseconds(0);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
