///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContentPhoto
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 7;11.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Ranorex.Delay.Seconds(1);
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 7;11.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("7;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Ranorex.Delay.Seconds(1);
        }

        public void Mouse_Up_ATag20150105RawThennowJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.Results.ATag20150105RawThennowJpg' at 91;13.", repo.ShowsWWE.Results.ATag20150105RawThennowJpgInfo);
            repo.ShowsWWE.Results.ATag20150105RawThennowJpg.MoveTo("91;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_ATag20150105RawThennowJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.Results.ATag20150105RawThennowJpg' at 91;13.", repo.ShowsWWE.Results.ATag20150105RawThennowJpgInfo);
            repo.ShowsWWE.Results.ATag20150105RawThennowJpg.MoveTo("91;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_ATag17()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.Results.ATag17' at 12;10.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.MoveTo("12;10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_ATag17()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.Results.ATag17' at 12;10.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.MoveTo("12;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_ATag01()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.Results.ATag01' at 4;5.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.MoveTo("4;5");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_ATag01()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.Results.ATag01' at 4;5.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.MoveTo("4;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_ATag20151()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.Results.ATag20151' at 9;6.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.MoveTo("9;6");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_ATag20151()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.Results.ATag20151' at 9;6.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.MoveTo("9;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_HttpQaWweAppCloud6WweComFeedsW2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 7;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.MoveTo("7;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 7;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.MoveTo("7;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_Dropdown()
        {
           // Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dropdown' at 86;23.", repo.Dropdown.SelfInfo);
          //  repo.Dropdown.Self.MoveTo("86;23");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_Dropdown()
        {
           // Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dropdown' at 86;23.", repo.Dropdown.SelfInfo);
           // repo.Dropdown.Self.MoveTo("86;23");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_EditPhotoTitleStyle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.EditPhotoTitleStyle' at 104;13.", repo.ShowsWWE.EditPhotoTitleStyleInfo);
            repo.ShowsWWE.EditPhotoTitleStyle.MoveTo("104;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_EditPhotoTitleStyle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.EditPhotoTitleStyle' at 104;13.", repo.ShowsWWE.EditPhotoTitleStyleInfo);
            repo.ShowsWWE.EditPhotoTitleStyle.MoveTo("104;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

       
        public void Key_Shortcut_EditPhotoTitle1()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Shift+D' Down with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo);
            Keyboard.PrepareFocus(repo.ShowsWWE.EditPhotoTitle);
            Keyboard.Down(System.Windows.Forms.Keys.D, 32, false);
        }

        public void Key_Shortcut_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Shift+LShiftKey' Down with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo);
            Keyboard.PrepareFocus(repo.ShowsWWE.EditPhotoTitle);
            Keyboard.Down(System.Windows.Forms.Keys.LShiftKey, 42, false);
        }

        public void Mouse_Up_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.EditPhotoTitle' at 181;12.", repo.ShowsWWE.EditPhotoTitleInfo);
            repo.ShowsWWE.EditPhotoTitle.MoveTo("181;12");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_EditPhotoTitle(String title)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.EditPhotoTitle' at 181;12.", repo.ShowsWWE.EditPhotoTitleInfo);
            repo.ShowsWWE.EditPhotoTitle.PressKeys(title);
           
        }

        public void ClickOnPhoto()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 60;13.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            //repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("60;13");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-4']/a[@innertext='Photo']");
        }
        public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        
      

        public void Key_Sequence_EditPhotoFid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 11}' with focus on 'ShowsWWE.EditPhotoFid'.", repo.ShowsWWE.EditPhotoFidInfo);
            repo.ShowsWWE.EditPhotoFid.PressKeys("{Back 1}");
        }

       

        public void Key_Sequence_EditPhotoFid3()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable $varPhotoNID with focus on 'ShowsWWE.EditPhotoFid'.", repo.ShowsWWE.EditPhotoFidInfo);
            repo.ShowsWWE.EditPhotoFid.PressKeys(varPhotoNID);
        }

        public void Key_Sequence_EditPhotoFid2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 1}' with focus on 'ShowsWWE.EditPhotoFid'.", repo.ShowsWWE.EditPhotoFidInfo);
            repo.ShowsWWE.EditPhotoFid.PressKeys("{Back 1}");
        }
         public void pressTab()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.");
            Keyboard.Press("{Tab}");
        }
    }
}