///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddContent_YouTube recording.
    /// </summary>
    [TestModule("744d5f8e-ca75-4a9e-b1fe-5e6166b3d849", ModuleType.Recording, 1)]
    public partial class AddContent_YouTube : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContent_YouTube instance = new AddContent_YouTube();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContent_YouTube()
        {
            varYTubeId = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContent_YouTube Instance
        {
            get { return instance; }
        }

#region Variables

        string _varYTubeId;

        /// <summary>
        /// Gets or sets the value of variable varYTubeId.
        /// </summary>
        [TestVariable("3eafbe76-19c9-4218-b29e-7cd0b28050c1")]
        public string varYTubeId
        {
            get { return _varYTubeId; }
            set { _varYTubeId = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_ClickOnYouTube();
            Delay.Milliseconds(0);
            
            Mouse_Click_EditYtid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditYtid(varYTubeId);
            Delay.Milliseconds(0);
            
            Mouse_Down_DragNDrop();
            Delay.Milliseconds(0);
            
            Mouse_Up_DragNDrop();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
