///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class AddContent_Poll
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear6' at 5;13.", repo.ShowsWWE.DropMeWhereIShouldAppear6Info);
            repo.ShowsWWE.InnerContent.MoveTo("50;50");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_DragNDrop()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpWweDevWweAppCloud14WweComF2' at 5;13.", repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF2Info);
            repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF2.MoveTo("5;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_EditPollNid1(String pollNid)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1234' with focus on 'ShowsWWE.EditPollNid'.", repo.ShowsWWE.EditPollNidInfo);
            repo.ShowsWWE.EditPollNid.PressKeys(pollNid);
        }

        public void Key_Sequence_EditPollNid()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ShowsWWE.EditPollNid'.", repo.ShowsWWE.EditPollNidInfo);
            repo.ShowsWWE.EditPollNid.PressKeys("{Back}");
        }

        public void Mouse_Up_EditPollNid()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.EditPollNid' at 21;11.", repo.ShowsWWE.EditPollNidInfo);
            //repo.ShowsWWE.EditPollNid.MoveTo("21;11");
           // Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
           clickOnObject("/dom[@caption='WWE']//input[#'edit-poll-nid']");
        }

        public void Mouse_ClickOnPoll()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpWweDevWweAppCloud14WweComF2' at 50;8.", repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF2Info);
           // repo.ShowsWWE.HttpWweDevWweAppCloud14WweComF2.Click("50;8");
            clickOnObject("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-8']/a[@innertext='Poll']");
        }
       public void clickOnObject(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}

        public void Mouse_Up_DropMeWhereIShouldAppear6()
        {
        }
    }
}