///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addContentTweet recording.
    /// </summary>
    [TestModule("8c8e17f0-d174-425c-b8c2-8aa5fb551e37", ModuleType.Recording, 1)]
    public partial class AddContentTweet : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static AddContentTweet instance = new AddContentTweet();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddContentTweet()
        {
            varNID = "1223455";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddContentTweet Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNID;

        /// <summary>
        /// Gets or sets the value of variable varNID.
        /// </summary>
        [TestVariable("9022968c-8311-4ca1-9e49-5a44c2460197")]
        public string varNID
        {
            get { return _varNID; }
            set { _varNID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1000ms.", new RecordItemIndex(0));
            Delay.Duration(1000, false);
            
            Mouse_Click_OnTweet();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(2));
            Delay.Duration(500, false);
            
            Mouse_Click_EditTweetSiid();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTweetSiid1();
            Delay.Milliseconds(0);
            
            Key_Sequence_EditTweetSiid();
            Delay.Milliseconds(0);
            
            Mouse_Down_HttpQaWweAppCloud6WweComFeedsW1();
            Delay.Milliseconds(0);
            
            Mouse_Up_DropMeWhereIShouldAppear();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
