///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The demo recording.
    /// </summary>
    [TestModule("9b02e4b7-57be-47ec-8cb8-992346a10d3d", ModuleType.Recording, 1)]
    public partial class Demo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static Demo instance = new Demo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Demo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Demo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive", "chrome", "", false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://qa.wwe-app.cloud6.wwe.com/f/styles/active_1/public/wweactive/photo/2015/01/1-7/raw_extra_teaser.jpg') on item 'ShowsWWE.HttpQaWweAppCloud6WweComFStyle'.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFStyleInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.ShowsWWE.HttpQaWweAppCloud6WweComFStyleInfo, "Src", "http://qa.wwe-app.cloud6.wwe.com/f/styles/active_1/public/wweactive/photo/2015/01/1-7/raw_extra_teaser.jpg");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=874,Height=378}) on item 'ShowsWWE.HttpQaWweAppCloud6WweComFStyle'.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFStyleInfo, new RecordItemIndex(2));
            Validate.CompareImage(repo.ShowsWWE.HttpQaWweAppCloud6WweComFStyleInfo, HttpQaWweAppCloud6WweComFStyle_Screenshot1, HttpQaWweAppCloud6WweComFStyle_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1' at 134;16.", repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1Info, new RecordItemIndex(3));
            repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1.Click("134;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='RT @Sloomzo: HAHAHAHA!! OH HELL YEAH! #WWE http://t.co/06IILFuykf') on item 'ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1'.", repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1Info, new RecordItemIndex(4));
            Validate.Attribute(repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash1Info, "InnerText", "RT @Sloomzo: HAHAHAHA!! OH HELL YEAH! #WWE http://t.co/06IILFuykf");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.TeamViewer' at 24;13.", repo.Explorer.TeamViewerInfo, new RecordItemIndex(5));
            repo.Explorer.TeamViewer.Click("24;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage HttpQaWweAppCloud6WweComFStyle_Screenshot1
        { get { return repo.ShowsWWE.HttpQaWweAppCloud6WweComFStyleInfo.GetScreenshot1(new Rectangle(0, 0, 874, 378)); } }

        Imaging.FindOptions HttpQaWweAppCloud6WweComFStyle_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,874,378;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
