///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImageCompare recording.
    /// </summary>
    [TestModule("5d98e250-d311-452b-8907-5f51b41db211", ModuleType.Recording, 1)]
    public partial class ImageCompare : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static ImageCompare instance = new ImageCompare();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImageCompare()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImageCompare Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive/manage' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive/manage", "chrome", "", false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SecondScreenTestSessionsDemo' at 171;7.", repo.ShowsWWE.SecondScreenTestSessionsDemoInfo, new RecordItemIndex(1));
            repo.ShowsWWE.SecondScreenTestSessionsDemo.Click("171;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 58;18.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info, new RecordItemIndex(2));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.Click("58;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditPhotoTitle' at 169;3.", repo.ShowsWWE.EditPhotoTitleInfo, new RecordItemIndex(3));
            repo.ShowsWWE.EditPhotoTitle.Click("169;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}est' with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo, new RecordItemIndex(4));
            repo.ShowsWWE.EditPhotoTitle.PressKeys("{LShiftKey down}T{LShiftKey up}est");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 8;5.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info, new RecordItemIndex(5));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.Click("8;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20151' at 21;5.", repo.ShowsWWE.Results.ATag20151Info, new RecordItemIndex(6));
            repo.ShowsWWE.Results.ATag20151.Click("21;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 9;7.", repo.ShowsWWE.Results.ATag01Info, new RecordItemIndex(7));
            repo.ShowsWWE.Results.ATag01.Click("9;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 8;7.", repo.ShowsWWE.Results.ATag17Info, new RecordItemIndex(8));
            repo.ShowsWWE.Results.ATag17.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.RawExtraTeaserJpg' at 58;2.", repo.ShowsWWE.Results.RawExtraTeaserJpgInfo, new RecordItemIndex(9));
            repo.ShowsWWE.Results.RawExtraTeaserJpg.Click("58;2");
            Delay.Milliseconds(200);
            
            Mouse_Down_HttpQaWweAppCloud6WweComFeedsW3();
            Delay.Milliseconds(0);
            
            Mouse_Up_DropMeWhereIShouldAppear1();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
