///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class ImageCompare
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
            
            
             //Open Production URL
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive' with browser 'Chrome'");
            Host.Local.OpenBrowser("http://qa.wwe-app.cloud6.wwe.com/admin/structure/taxonomy/shows","Chrome");
            Delay.Seconds(15);
            ATag addTerm = "/dom[@domain='qa.wwe-app.cloud6.wwe.com']//div[#'content']//a[@innertext='Add term']";
            addTerm.Click();
         
		            
        }

        private void imageCaptureSteps(){
        	  String CurrentTimestamp = System.DateTime.Now.ToString("dd_MM_yyyy_HH_mm_ss");
			Console.WriteLine(CurrentTimestamp);
        	
			String name1="2a_"+CurrentTimestamp+".png";
        	Console.WriteLine(name1);
			name1="D:/CaptureImage/"+name1;    	
				
            //Get the Object from Production URL
            Report.Log(ReportLevel.Info, "Snapshot", "Capturing Screenshot from Production URL");
        	Bitmap bmp1 = get_Snapshot("/dom[5]//div[#'content-item-44682-container']/img[@src='http://qa.wwe-app.cloud6.wwe.com/f/styles/active_1/public/wweactive/photo/2015/01/1-7/raw_extra_teaser.jpg']");
			bmp1.Save(name1, System.Drawing.Imaging.ImageFormat.Png);
        	
			
			//Compare Images:-
			if (Ranorex.Imaging.Compare(bmp1,bmp1,0.95))
        		Ranorex.Report.Success("Images are Same and clicked successfully");
        }
        private Bitmap get_Snapshot(string xpath)
        		{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        			if(elements.Count>0)
		        	{
		        		return elements[0].CaptureCompressedImage();
		        	}
        			else
		        	{
		        		return null;
		        	}
			}

        public void Mouse_Up_DropMeWhereIShouldAppear1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 10;11.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info);
            repo.ShowsWWE.DropMeWhereIShouldAppear1.MoveTo("05;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 10;11.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("10;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Unknown element222605448 = "/form[@title='WWE - Google Chrome']/element[@controlid='222605448']";
            Mouse.MoveTo(element222605448);
        }
    }
}