///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ManageContentNew recording.
    /// </summary>
    [TestModule("9ddf6a5e-3866-4599-a4c2-46709d916400", ModuleType.Recording, 1)]
    public partial class ManageContentNew : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static ManageContentNew instance = new ManageContentNew();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ManageContentNew()
        {
            varURL = "http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive/manage";
            varBrowser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ManageContentNew Instance
        {
            get { return instance; }
        }

#region Variables

        string _varBrowser;

        /// <summary>
        /// Gets or sets the value of variable varBrowser.
        /// </summary>
        [TestVariable("0a309f2b-72c9-4279-8898-de65cb8a8225")]
        public string varBrowser
        {
            get { return _varBrowser; }
            set { _varBrowser = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("c5e7ae4e-7777-4619-a119-8fd79de97e0d")]
        public string varURL
        {
            get { return repo.varURL; }
            set { repo.varURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            ManageContentNew_Open_Browser();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Mouse_Click_SecondScreenTestSessionsDemo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(3));
            Delay.Duration(10000, false);
            
            Mouse_Click_UiAccordionAccordionHeader6();
            Delay.Milliseconds(0);
            
            Mouse_Click_HttpQaWweAppCloud6WweComFeedsW();
            Delay.Milliseconds(0);
            
            Mouse_Click_RTAtSloomzoHAHAHAHAOHHELLYEAHHash();
            Delay.Milliseconds(0);
            
            Mouse_Down_HttpQaWweAppCloud6WweComFeedsW1();
            Delay.Milliseconds(0);
            
            Mouse_Up_DropMeWhereIShouldAppear();
            Delay.Milliseconds(0);
            
            Mouse_Click_HttpQaWweAppCloud6WweComFeedsW3();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(10));
            Delay.Duration(500, false);
            
            Mouse_Click_EditPhotoTitle();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(12));
            Delay.Duration(500, false);
            
            Key_Sequence_EditPhotoTitle();
            Delay.Milliseconds(0);
            
            Mouse_Click_HttpQaWweAppCloud6WweComFeedsW2();
            Delay.Milliseconds(0);
            
            Mouse_Click_ATag20151();
            Delay.Milliseconds(0);
            
            Mouse_Click_ATag01();
            Delay.Milliseconds(0);
            
            Mouse_Click_ATag17();
            Delay.Milliseconds(0);
            
            Mouse_Click_RawExtraTeaserJpg();
            Delay.Milliseconds(0);
            
            Mouse_Down_HttpQaWweAppCloud6WweComFeedsW3();
            Delay.Milliseconds(0);
            
            Mouse_Up_DropMeWhereIShouldAppear1();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
