///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class ManageContentNew
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
      
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
 		public static Bitmap firstImage;
        public void Mouse_Up_DropMeWhereIShouldAppear1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 8;9.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info);
            repo.ShowsWWE.DropMeWhereIShouldAppear1.MoveTo("8;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 8;9.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("8;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_ATag20150105RawRescuerouteJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20150105RawRescuerouteJpg' at 108;13.", repo.ShowsWWE.Results.ATag20150105RawRescuerouteJpgInfo);
            repo.ShowsWWE.Results.ATag20150105RawRescuerouteJpg.Click("108;13");
        }

        public void Mouse_Click_ATag17()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 6;8.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.Click("6;8");
        }

        public void Mouse_Click_ATag01()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 5;11.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.Click("5;11");
        }

        public void Mouse_Click_ATag20151()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag20151' at 13;7.", repo.ShowsWWE.Results.ATag20151Info);
            repo.ShowsWWE.Results.ATag20151.Click("13;7");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 10;12.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.Click("10;12");
        }

        public void Key_Sequence_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}D{LShiftKey up}emp{Back}otest' with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo);
            repo.ShowsWWE.EditPhotoTitle.PressKeys("{LShiftKey down}D{LShiftKey up}emp{Back}otest");
        }

        public void Mouse_Click_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditPhotoTitle' at 92;12.", repo.ShowsWWE.EditPhotoTitleInfo);
           // repo.ShowsWWE.EditPhotoTitle.Click("92;12");
            get_Object("/dom[@domain='qa.wwe-app.cloud6.wwe.com']//h3[#'ui-accordion-accordion-header-4']/a[@innertext='Photo']");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 48;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.Click("48;8");
        }

        public void Mouse_Up_DropMeWhereIShouldAppear()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 12;14.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("12;14");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 12;14.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("12;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
        }

        public void Mouse_Click_RTAtSloomzoHAHAHAHAOHHELLYEAHHash()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash' at 107;-1.", repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHashInfo);
            repo.ShowsWWE.RTAtSloomzoHAHAHAHAOHHELLYEAHHash.Click("107;-1");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW' at 14;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsWInfo);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW.Click("14;8");
        }

        public void Mouse_Click_UiAccordionAccordionHeader6()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.UiAccordionAccordionHeader6' at 134;7.", repo.ShowsWWE.UiAccordionAccordionHeader6Info);
            repo.ShowsWWE.UiAccordionAccordionHeader6.Click("134;7");
        }

        public void Mouse_Click_SecondScreenTestSessionsDemo()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SecondScreenTestSessionsDemo' at 188;12.", repo.ShowsWWE.SecondScreenTestSessionsDemoInfo);
           // repo.ShowsWWE.SecondScreenTestSessionsDemo.Click("188;12");
           get_Object("/dom[@domain='qa.wwe-app.cloud6.wwe.com']//table[#'planning-table']/tbody/tr[1]/td[2]/a[@class='episode-title']");
        }

        public void ManageContentNew_Open_Browser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varURL with browser specified by variable $varBrowser in normal mode.");
            Host.Local.OpenBrowser(varURL, varBrowser, "", false, false);
        }
       private void get_Object(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}
         private void storeImage(){
        	
            String CurrentTimestamp = System.DateTime.Now.ToString("dd_MM_yyyy_HH_mm_ss");
			Console.WriteLine(CurrentTimestamp);
        	
			String name1="2a_"+CurrentTimestamp+".png";
        	Console.WriteLine(name1);
			//name1="D:/CaptureImage/"+name1;    	
			name1="D:/CaptureImage/firstImage.png"; 	
            //Get the Object from Production URL
            Report.Log(ReportLevel.Info, "Snapshot", "Capturing Screenshot from Production URL");
        	Bitmap bmp1= get_Snapshot("/dom[@domain='qa.wwe-app.cloud6.wwe.com']//div[#'content-item-44689']/?/?/img[@src='http://qa.wwe-app.cloud6.wwe.com/f/styles/teaser_small/public/wweactive/photo/2015/01/1-7/raw_extra_teaser.jpg']");
			bmp1.Save(name1, System.Drawing.Imaging.ImageFormat.Png);
			
        	//Compare Images:-
        		Ranorex.Report.Success("Image saved successfully");
	
        }
        private Bitmap get_Snapshot(string xpath)
        		{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        			if(elements.Count>0)
		        	{
		        		return elements[0].CaptureCompressedImage();
		        	}
        			else
		        	{
		        		return null;
		        	}
			}

        public void Mouse_Click_RawExtraTeaserJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.RawExtraTeaserJpg' at 78;5.", repo.ShowsWWE.Results.RawExtraTeaserJpgInfo);
            repo.ShowsWWE.Results.RawExtraTeaserJpg.Click("78;5");
        }
		
    }
  
}