///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ManageContent1 recording.
    /// </summary>
    [TestModule("24089430-5a21-4bfc-a3e3-12133950b315", ModuleType.Recording, 1)]
    public partial class ManageContent1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static ManageContent1 instance = new ManageContent1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ManageContent1()
        {
            varURL = "http://qa.wwe-app.cloud6.wwe.com/feeds/wweactive/manage";
            varBrowser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ManageContent1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varBrowser;

        /// <summary>
        /// Gets or sets the value of variable varBrowser.
        /// </summary>
        [TestVariable("b0127d09-9d5e-42f7-8761-d1a5fd15e835")]
        public string varBrowser
        {
            get { return _varBrowser; }
            set { _varBrowser = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("425fbf33-9dbe-4498-8f02-b96ee4781a49")]
        public string varURL
        {
            get { return repo.varURL; }
            set { repo.varURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varURL with browser specified by variable $varBrowser in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser(varURL, varBrowser, "", false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.ThirdShowsSecondShows' at 120;13.", repo.ShowsWWE.ThirdShowsSecondShowsInfo, new RecordItemIndex(1));
            repo.ShowsWWE.ThirdShowsSecondShows.Click("120;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.UiAccordionAccordionHeader6' at 127;5.", repo.ShowsWWE.UiAccordionAccordionHeader6Info, new RecordItemIndex(2));
            repo.ShowsWWE.UiAccordionAccordionHeader6.Click("127;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW' at 14;6.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsWInfo, new RecordItemIndex(3));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW.Click("14;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.RTAtWadeBarrettHowAboutThatAtWayne' at 112;7.", repo.ShowsWWE.RTAtWadeBarrettHowAboutThatAtWayneInfo, new RecordItemIndex(4));
            repo.ShowsWWE.RTAtWadeBarrettHowAboutThatAtWayne.Click("112;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 11;13.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info, new RecordItemIndex(5));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("11;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 11;13.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo, new RecordItemIndex(6));
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("11;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 64;12.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info, new RecordItemIndex(7));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.Click("64;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditPhotoTitle' at 198;10.", repo.ShowsWWE.EditPhotoTitleInfo, new RecordItemIndex(8));
            repo.ShowsWWE.EditPhotoTitle.Click("198;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}est{LShiftKey down}D{LShiftKey up}emo' with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo, new RecordItemIndex(9));
            repo.ShowsWWE.EditPhotoTitle.PressKeys("{LShiftKey down}T{LShiftKey up}est{LShiftKey down}D{LShiftKey up}emo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 8;6.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info, new RecordItemIndex(10));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.Photo' at 20;8.", repo.ShowsWWE.Results.PhotoInfo, new RecordItemIndex(11));
            repo.ShowsWWE.Results.Photo.Click("20;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag2013' at 11;5.", repo.ShowsWWE.Results.ATag2013Info, new RecordItemIndex(12));
            repo.ShowsWWE.Results.ATag2013.Click("11;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag04' at 6;5.", repo.ShowsWWE.Results.ATag04Info, new RecordItemIndex(13));
            repo.ShowsWWE.Results.ATag04.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 8;2.", repo.ShowsWWE.Results.ATag17Info, new RecordItemIndex(14));
            repo.ShowsWWE.Results.ATag17.Click("8;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.RawActiveTuneInJpg' at 27;4.", repo.ShowsWWE.Results.RawActiveTuneInJpgInfo, new RecordItemIndex(15));
            repo.ShowsWWE.Results.RawActiveTuneInJpg.Click("27;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 4;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info, new RecordItemIndex(16));
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("4;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 4;8.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info, new RecordItemIndex(17));
            repo.ShowsWWE.DropMeWhereIShouldAppear1.MoveTo("4;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
