///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class ManageContent
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_DropMeWhereIShouldAppear12()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 6;11.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info);
            repo.ShowsWWE.DropMeWhereIShouldAppear1.MoveTo("6;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW31()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 6;11.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("6;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_DropMeWhereIShouldAppear11()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear1' at 9;7.", repo.ShowsWWE.DropMeWhereIShouldAppear1Info);
            repo.ShowsWWE.DropMeWhereIShouldAppear1.MoveTo("9;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3' at 9;7.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW3.MoveTo("9;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_RawExtraTeaserJpg()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.RawExtraTeaserJpg' at 68;1.", repo.ShowsWWE.Results.RawExtraTeaserJpgInfo);
            repo.ShowsWWE.Results.RawExtraTeaserJpg.Click("68;1");
        }

        public void Mouse_Click_ATag17()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag17' at 10;10.", repo.ShowsWWE.Results.ATag17Info);
            repo.ShowsWWE.Results.ATag17.Click("10;10");
        }

        public void Mouse_Click_ATag01()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag01' at 8;9.", repo.ShowsWWE.Results.ATag01Info);
            repo.ShowsWWE.Results.ATag01.Click("8;9");
        }

        public void Mouse_Click_ATag2015()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.ATag2015' at 14;1.", repo.ShowsWWE.Results.ATag2015Info);
            repo.ShowsWWE.Results.ATag2015.Click("14;1");
        }

        public void Mouse_Click_Photo()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Results.Photo' at 20;3.", repo.ShowsWWE.Results.PhotoInfo);
            repo.ShowsWWE.Results.Photo.Click("20;3");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2' at 10;8.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW2.Click("10;8");
        }

        public void Set_Value_EditPhotoTitleStyle()
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'smackdown' on item 'ShowsWWE.EditPhotoTitleStyle'.", repo.ShowsWWE.EditPhotoTitleStyleInfo);
            repo.ShowsWWE.EditPhotoTitleStyle.Element.SetAttributeValue("TagValue", "smackdown");
        }

        public void Key_Sequence_EditPhotoTitle1()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P{LShiftKey up}ic' with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo);
            repo.ShowsWWE.EditPhotoTitle.PressKeys("P{LShiftKey up}ic");
        }

        public void Key_Sequence_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}D{LShiftKey up}emo{LShiftKey down}' with focus on 'ShowsWWE.EditPhotoTitle'.", repo.ShowsWWE.EditPhotoTitleInfo);
            repo.ShowsWWE.EditPhotoTitle.PressKeys("{LShiftKey down}D{LShiftKey up}emo{LShiftKey down}");
        }

        public void Mouse_Click_EditPhotoTitle()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.EditPhotoTitle' at 79;10.", repo.ShowsWWE.EditPhotoTitleInfo);
           // repo.ShowsWWE.EditPhotoTitle.Click("79;10");
           get_Object("/dom[@caption='WWE']//h3[#'ui-accordion-accordion-header-4']/a[@innertext='Photo']");
        }

        public void Mouse_Click_UiAccordionAccordionHeader4()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.UiAccordionAccordionHeader4' at 82;12.", repo.ShowsWWE.UiAccordionAccordionHeader4Info);
            repo.ShowsWWE.UiAccordionAccordionHeader4.Click("82;12");
        }

        public void Mouse_Up_DropMeWhereIShouldAppear2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 9;15.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("9;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW12()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 9;15.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("9;15");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Up_DropMeWhereIShouldAppear1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 11;14.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("11;14");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW11()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 11;14.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("11;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 4;13.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.Click("4;13");
        }

        public void Mouse_Up_DropMeWhereIShouldAppear()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 14;10.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("10;10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 14;10.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("14;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_ATagAtHeymanHustleCanYouLinkMeToTh()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.ATagAtHeymanHustleCanYouLinkMeToTh' at 93;2.", repo.ShowsWWE.ATagAtHeymanHustleCanYouLinkMeToThInfo);
            repo.ShowsWWE.ATagAtHeymanHustleCanYouLinkMeToTh.Click("93;2");
        }

        public void Mouse_Click_HttpQaWweAppCloud6WweComFeedsW()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW' at 9;11.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsWInfo);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW.Click("9;11");
        }

        public void Mouse_Click_UiAccordionAccordionHeader6()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.UiAccordionAccordionHeader6' at 95;19.", repo.ShowsWWE.UiAccordionAccordionHeader6Info);
            repo.ShowsWWE.UiAccordionAccordionHeader6.Click("95;19");
        }

        public void Mouse_Click_SecondScreenTestSessionsDemo()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.SecondScreenTestSessionsDemo' at 152;3.", repo.ShowsWWE.SecondScreenTestSessionsDemoInfo);
            //repo.ShowsWWE.SecondScreenTestSessionsDemo.Click("152;3");
            get_Object("/dom[@caption='WWE']//table[#'planning-table']/tbody/tr/td[2]/a[@class='episode-title']");
        }

        public void manageContent_Open_Browser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varURL with browser specified by variable $varBrowser in normal mode.");
            Host.Local.OpenBrowser(varURL, varBrowser, "", false, false);
        }
		private void get_Object(string xpath)
        	{
				var elements = Ranorex.Host.Local.Find<Ranorex.Unknown>(xpath);
        		
				if(elements.Count>0)
		        	{
        			 elements[0].Click();
		        	}
			}
		public void Mouse_Down_DropMeWhereIShouldAppear()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 14;10.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("14;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_HttpQaWweAppCloud6WweComFeedsW13()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1' at 11;12.", repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1Info);
            repo.ShowsWWE.HttpQaWweAppCloud6WweComFeedsW1.MoveTo("11;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
              Delay.Seconds(2);
        }

        public void Mouse_Up_DropMeWhereIShouldAppear3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ShowsWWE.DropMeWhereIShouldAppear' at 11;12.", repo.ShowsWWE.DropMeWhereIShouldAppearInfo);
            repo.ShowsWWE.DropMeWhereIShouldAppear.MoveTo("11;12");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Seconds(2);
        }
    }
}