///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The mobileSecondScreen recording.
    /// </summary>
    [TestModule("f7e3d08b-3598-44d8-8364-a1c827027781", ModuleType.Recording, 1)]
    public partial class MobileSecondScreen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static MobileSecondScreen instance = new MobileSecondScreen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MobileSecondScreen()
        {
            varDeviceName = "tab4";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MobileSecondScreen Instance
        {
            get { return instance; }
        }

#region Variables

        string _varDeviceName;

        /// <summary>
        /// Gets or sets the value of variable varDeviceName.
        /// </summary>
        [TestVariable("beb7cbc2-29d2-4cc8-9edc-63c4197b4348")]
        public string varDeviceName
        {
            get { return _varDeviceName; }
            set { _varDeviceName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            mobileSecondScreen_Run_Mobile_App(varDeviceName);
            Delay.Milliseconds(0);
            
            DoDelay();
            Delay.Milliseconds(0);
            
            Touch_Home();
            Delay.Milliseconds(0);
            
            Touch_RStringSecondScreen();
            Delay.Milliseconds(0);
            
            Validate_ComWweUniverse();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
