///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MobileRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    [RepositoryFolder("11dcaba6-d52f-4903-8888-66a9f4925eaa")]
    public partial class MobileRepository : RepoGenBaseFolder
    {
        static MobileRepository instance = new MobileRepository();
        MobileRepositoryFolders.ComWweUniverseAppFolder _comwweuniverse;

        /// <summary>
        /// Gets the singleton class instance representing the MobileRepository element repository.
        /// </summary>
        [RepositoryFolder("11dcaba6-d52f-4903-8888-66a9f4925eaa")]
        public static MobileRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MobileRepository() 
            : base("MobileRepository", "/", null, 0, false, "11dcaba6-d52f-4903-8888-66a9f4925eaa", ".\\RepositoryImages\\mobileRepository11dcaba6.rximgres")
        {
            _comwweuniverse = new MobileRepositoryFolders.ComWweUniverseAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("11dcaba6-d52f-4903-8888-66a9f4925eaa")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComWweUniverse folder.
        /// </summary>
        [RepositoryFolder("aa66e8c8-5de7-4943-bdc8-530689e1ae79")]
        public virtual MobileRepositoryFolders.ComWweUniverseAppFolder ComWweUniverse
        {
            get { return _comwweuniverse; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    public partial class MobileRepositoryFolders
    {
        /// <summary>
        /// The ComWweUniverseAppFolder folder.
        /// </summary>
        [RepositoryFolder("aa66e8c8-5de7-4943-bdc8-530689e1ae79")]
        public partial class ComWweUniverseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new ComWweUniverse  folder.
            /// </summary>
            public ComWweUniverseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComWweUniverse", "/mobileapp[@title='com.wwe.universe']", parentFolder, 30000, null, false, "aa66e8c8-5de7-4943-bdc8-530689e1ae79", "")
            {
                _homeInfo = new RepoItemInfo(this, "Home", "?/?/toolbar/?/?/container[@contentdescription='WWE, Navigate up']/?/?/picture[@rid='home']", 30000, null, "7ea2a777-feda-4ea1-97b1-749dfb422369");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa66e8c8-5de7-4943-bdc8-530689e1ae79")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa66e8c8-5de7-4943-bdc8-530689e1ae79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("7ea2a777-feda-4ea1-97b1-749dfb422369")]
            public virtual Ranorex.Picture Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("7ea2a777-feda-4ea1-97b1-749dfb422369")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}