///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class MobileSecondScreen
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

       
        public void mobileSecondScreen_Run_Mobile_App(String deviceName)
        {
            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.wwe.universe' on device 'tab4'.");
            Host.Local.RunMobileApp(deviceName, "com.wwe.universe");
        }

        public void Validate_ComWweUniverse()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComWweUniverse'.", repo.ComWweUniverse.SelfInfo);
            Validate.Attribute(repo.ComWweUniverse.SelfInfo, "Visible", "True");
        }

        public void Touch_RStringSecondScreen()
        {
            Report.Log(ReportLevel.Info, "Touch", "LongTouch item 'ComWweUniverse.RStringSecondScreen' at 94;46", repo.ComWweUniverse.RStringSecondScreenInfo);
            repo.ComWweUniverse.RStringSecondScreen.LongTouch("94;46");
        }

        public void Touch_Home()
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComWweUniverse.Home' at Center", repo.ComWweUniverse.HomeInfo);
            repo.ComWweUniverse.Home.Touch();
        }

        public void DoDelay()
        {
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.");
            Delay.Duration(10000, false);
        }

    }
}