///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTweet_Web recording.
    /// </summary>
    [TestModule("6aa5c1fe-700f-4fcc-8205-09bc2d7934b1", ModuleType.Recording, 1)]
    public partial class VerifyTweet_Web : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static VerifyTweet_Web instance = new VerifyTweet_Web();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTweet_Web()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTweet_Web Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_Tweets();
            Delay.Milliseconds(0);
            
            Validate_Tweets();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Tweets_Screenshot1
        { get { return repo.ShowsWWE.TweetsInfo.GetScreenshot1(new Rectangle(0, 0, 410, 57)); } }

        Imaging.FindOptions Tweets_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,410,57;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
