///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTweetText_Web recording.
    /// </summary>
    [TestModule("0d0e1ef2-8207-46c2-bacb-a6259c8065de", ModuleType.Recording, 1)]
    public partial class VerifyTweetText_Web : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static VerifyTweetText_Web instance = new VerifyTweetText_Web();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTweetText_Web()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTweetText_Web Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=874,Height=82}) on item 'ShowsWWE.HeaderClearfix1'.", repo.ShowsWWE.HeaderClearfix1Info, new RecordItemIndex(0));
            Validate.CompareImage(repo.ShowsWWE.HeaderClearfix1Info, HeaderClearfix1_Screenshot1, HeaderClearfix1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.DeviceAndroidRelease131' at 908;545.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(1));
            repo.ShowsWWE.DeviceAndroidRelease131.Click("908;545");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 6}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(2));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down 6}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.DeviceAndroidRelease131' at 912;550.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(3));
            repo.ShowsWWE.DeviceAndroidRelease131.Click("912;550");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 20}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(4));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down 20}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.DivTagAtJCLayfieldRomanRigesBitToB' at 817;50.", repo.ShowsWWE.DivTagAtJCLayfieldRomanRigesBitToBInfo, new RecordItemIndex(5));
            repo.ShowsWWE.DivTagAtJCLayfieldRomanRigesBitToB.Click("817;50");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 5}{Down 4}{Down}{Down}{Down}{Down}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(6));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down 5}{Down 4}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage HeaderClearfix1_Screenshot1
        { get { return repo.ShowsWWE.HeaderClearfix1Info.GetScreenshot1(new Rectangle(0, 0, 874, 82)); } }

        Imaging.FindOptions HeaderClearfix1_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,874,82;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
