///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SecondScreen
{
    public partial class VerifyTweet_Web
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_Tweets()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=410,Height=57}) on item 'ShowsWWE.Tweets'.", repo.ShowsWWE.TweetsInfo);
            Validate.CompareImage(repo.ShowsWWE.TweetsInfo, Tweets_Screenshot1, Tweets_Screenshot1_Options);
        }

        public void Mouse_Click_Tweets()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.Tweets' at 111;16.", repo.ShowsWWE.TweetsInfo);
            repo.ShowsWWE.Tweets.Click("111;16");
        }

    }
}