///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyPoll_Web recording.
    /// </summary>
    [TestModule("16873b84-3474-4d3c-aab9-f96deea23618", ModuleType.Recording, 1)]
    public partial class VerifyPoll_Web : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static VerifyPoll_Web instance = new VerifyPoll_Web();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyPoll_Web()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyPoll_Web Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=822,Height=29}) on item 'ShowsWWE.H2TagQuestion'.", repo.ShowsWWE.H2TagQuestionInfo, new RecordItemIndex(0));
            Validate.CompareImage(repo.ShowsWWE.H2TagQuestionInfo, H2TagQuestion_Screenshot1, H2TagQuestion_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.FeedContent' at 853;451.", repo.ShowsWWE.FeedContentInfo, new RecordItemIndex(1));
            repo.ShowsWWE.FeedContent.Click("853;451");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 6}{Down 8}{Down}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(2));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down 6}{Down 8}{Down}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage H2TagQuestion_Screenshot1
        { get { return repo.ShowsWWE.H2TagQuestionInfo.GetScreenshot1(new Rectangle(0, 0, 822, 29)); } }

        Imaging.FindOptions H2TagQuestion_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,822,29;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
