///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyPhotoGroup_Web recording.
    /// </summary>
    [TestModule("793a9585-2e59-417e-aaea-284949af6019", ModuleType.Recording, 1)]
    public partial class VerifyPhotoGroup_Web : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static VerifyPhotoGroup_Web instance = new VerifyPhotoGroup_Web();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyPhotoGroup_Web()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyPhotoGroup_Web Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=822,Height=29}) on item 'ShowsWWE.DemoTest'.", repo.ShowsWWE.DemoTestInfo, new RecordItemIndex(0));
            Validate.CompareImage(repo.ShowsWWE.DemoTestInfo, DemoTest_Screenshot1, DemoTest_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.HeaderClearfix1' at 15;17.", repo.ShowsWWE.HeaderClearfix1Info, new RecordItemIndex(1));
            repo.ShowsWWE.HeaderClearfix1.Click("15;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage DemoTest_Screenshot1
        { get { return repo.ShowsWWE.DemoTestInfo.GetScreenshot1(new Rectangle(0, 0, 822, 29)); } }

        Imaging.FindOptions DemoTest_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,822,29;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
