///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SecondScreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyVideo_Web recording.
    /// </summary>
    [TestModule("742db51a-6258-457d-a3a1-bf3bd02e4d02", ModuleType.Recording, 1)]
    public partial class VerifyVideo_Web : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SecondScreenRepository repository.
        /// </summary>
        public static SecondScreenRepository repo = SecondScreenRepository.Instance;

        static VerifyVideo_Web instance = new VerifyVideo_Web();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyVideo_Web()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyVideo_Web Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=874,Height=611}) on item 'ShowsWWE.FeedContent'.", repo.ShowsWWE.FeedContentInfo, new RecordItemIndex(0));
            Validate.CompareImage(repo.ShowsWWE.FeedContentInfo, FeedContent_Screenshot1, FeedContent_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.DeviceAndroidRelease131' at 906;589.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(1));
            repo.ShowsWWE.DeviceAndroidRelease131.Click("906;589");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 2}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(2));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down 2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShowsWWE.FeedContent' at 844;567.", repo.ShowsWWE.FeedContentInfo, new RecordItemIndex(3));
            repo.ShowsWWE.FeedContent.Click("844;567");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down 2}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'ShowsWWE.DeviceAndroidRelease131'.", repo.ShowsWWE.DeviceAndroidRelease131Info, new RecordItemIndex(4));
            repo.ShowsWWE.DeviceAndroidRelease131.PressKeys("{Down}{Down}{Down 2}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage FeedContent_Screenshot1
        { get { return repo.ShowsWWE.FeedContentInfo.GetScreenshot1(new Rectangle(0, 0, 874, 611)); } }

        Imaging.FindOptions FeedContent_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,874,611;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
